/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import entity.Tuna;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

/**
 * Class generated by NetBeans.
 * Implementation of the Facade class.
 * 
 * @author Vuong Dinh, Parthashokbh Chauhan, Khanh Vuviet, Aksharbhavin Chauhan, Shubham Sachdeva
 */
@Stateless
public class TunaFacade extends AbstractFacade<Tuna> implements TunaFacadeRemote {

    @PersistenceContext(unitName = "Assignment4-ejbPU")
    private EntityManager em;

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    public TunaFacade() {
        super(Tuna.class);
    }
    
}
