/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import entity.Tuna;
import java.util.List;
import javax.ejb.Remote;

/**
 * Class generated by NetBeans.
 * Interface to handle remote database functionality
 * 
 * @author Vuong Dinh, Parthashokbh Chauhan, Khanh Vuviet, Aksharbhavin Chauhan, Shubham Sachdeva
 */
@Remote
public interface TunaFacadeRemote {

    void create(Tuna Tuna);

    void edit(Tuna Tuna);

    void remove(Tuna Tuna);

    Tuna find(Object id);

    List<Tuna> findAll();

    List<Tuna> findRange(int[] range);

    int count();
    
}
